--- #YAML:1.0
name:                Games-Go-SGF-Grove
version:             0.1
abstract:            SGF the Perl way
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
